DEBUG 2020-12-02 16:23:35.510 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-02 16:23:35.510 UTC: 	 Running on: Linux lxplus769.cern.ch 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-02 16:23:35.510 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-02 16:23:35.510 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
INFO 2020-12-02 16:23:35.511 UTC: 	 Will use CRAB configuration file ./CrabJobsSrc/SingleEle/crab3_analysis_seleB.py
DEBUG 2020-12-02 16:23:35.512 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-12-02 16:23:35.518 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-12-02 16:23:35.518 UTC: 	 Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab_fullrun2_2017_pujetID_version5_loose_seleB_v1' already exists 
Please change the requestName in the config file
ERROR 2020-12-02 16:23:35.518 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab_fullrun2_2017_pujetID_version5_loose_seleB_v1' already exists 
Please change the requestName in the config file
INFO 2020-12-02 16:23:35.522 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-12-02 16:23:35.836 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-02 16:23:35.837 UTC: 	 Running on: Linux lxplus769.cern.ch 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-02 16:23:35.837 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-02 16:23:35.837 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
INFO 2020-12-02 16:23:35.838 UTC: 	 Will use CRAB configuration file ./CrabJobsSrc/SingleEle/crab3_analysis_seleC.py
DEBUG 2020-12-02 16:23:35.838 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-12-02 16:23:35.841 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-12-02 16:23:35.841 UTC: 	 Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab_fullrun2_2017_pujetID_version5_loose_seleC' already exists 
Please change the requestName in the config file
ERROR 2020-12-02 16:23:35.841 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab_fullrun2_2017_pujetID_version5_loose_seleC' already exists 
Please change the requestName in the config file
INFO 2020-12-02 16:23:35.843 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-12-02 16:23:36.163 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-02 16:23:36.163 UTC: 	 Running on: Linux lxplus769.cern.ch 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-02 16:23:36.163 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-02 16:23:36.163 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
INFO 2020-12-02 16:23:36.164 UTC: 	 Will use CRAB configuration file ./CrabJobsSrc/SingleEle/crab3_analysis_seleD.py
DEBUG 2020-12-02 16:23:36.165 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-12-02 16:23:36.168 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-12-02 16:23:36.168 UTC: 	 Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab_fullrun2_2017_pujetID_version5_loose_seleD' already exists 
Please change the requestName in the config file
ERROR 2020-12-02 16:23:36.169 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab_fullrun2_2017_pujetID_version5_loose_seleD' already exists 
Please change the requestName in the config file
INFO 2020-12-02 16:23:36.171 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-12-02 16:23:36.539 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-02 16:23:36.540 UTC: 	 Running on: Linux lxplus769.cern.ch 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-02 16:23:36.540 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-02 16:23:36.540 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
INFO 2020-12-02 16:23:36.542 UTC: 	 Will use CRAB configuration file ./CrabJobsSrc/SingleEle/crab3_analysis_seleE.py
DEBUG 2020-12-02 16:23:36.542 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-12-02 16:23:36.546 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-12-02 16:23:36.546 UTC: 	 Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab_fullrun2_2017_pujetID_version5_loose_seleE' already exists 
Please change the requestName in the config file
ERROR 2020-12-02 16:23:36.546 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab_fullrun2_2017_pujetID_version5_loose_seleE' already exists 
Please change the requestName in the config file
INFO 2020-12-02 16:23:36.548 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
DEBUG 2020-12-02 16:23:36.872 UTC: 	 CRAB Client version: v3.201110
DEBUG 2020-12-02 16:23:36.872 UTC: 	 Running on: Linux lxplus769.cern.ch 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-12-02 16:23:36.872 UTC: 	 Executing command: 'submit'
DEBUG 2020-12-02 16:23:36.872 UTC: 	 Found CRAB cache file /afs/cern.ch/user/j/jipeng/.crab3
INFO 2020-12-02 16:23:36.873 UTC: 	 Will use CRAB configuration file ./CrabJobsSrc/SingleEle/crab3_analysis_seleF.py
DEBUG 2020-12-02 16:23:36.873 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-12-02 16:23:36.877 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-12-02 16:23:36.877 UTC: 	 Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab_fullrun2_2017_pujetID_version5_loose_seleF' already exists 
Please change the requestName in the config file
ERROR 2020-12-02 16:23:36.877 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.00/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab_fullrun2_2017_pujetID_version5_loose_seleF' already exists 
Please change the requestName in the config file
INFO 2020-12-02 16:23:36.879 UTC: 	 Log file is /afs/cern.ch/work/j/jipeng/Run2VBSWG_v2/17/17_loose_for_analysis/CMSSW_10_2_18/src/VAJets/PKUTreeMaker/test/crab.log
